name: Maestro Check Schemas
on:
  push:
    branches: [ 'main' ]
    paths:
      - 'maestro/**'
      - 'demos/**'
      - 'tools/update_all_readme.sh'
  pull_request:
    branches: [ 'main' ]
    paths:
      - 'maestro/**'
      - 'demos/**'
      - 'tools/update_all_readme.sh'
jobs:
  check-schemas:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Setup poetry
        run: |
          pipx ensurepath
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"
          pipx install poetry
          poetry self add poetry-plugin-shell
      - name: Install dependencies
        run: |
          cd maestro
          poetry install
          poetry run pip install beeai-framework
      - name: Filter changed files for demos
        id: filter
        uses: dorny/paths-filter@v2
        with:
          filters: |
            demos:
              - 'demos/**'

      - name: Update README diagrams
        if: steps.filter.outputs.demos == 'true'
        run: |
          # Go to project root (from maestro folder) and run the update script
          cd maestro
          cd ..
          chmod +x tools/update_all_readme.sh
          ./tools/update_all_readme.sh

      - name: Check schema
        run: |
          cd maestro
          poetry run tools/check-schemas.sh
